# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: data extraction pipeline workflow

on:
  push:
    tags:
     # add different proper testing for releases
      - '!refs/tags/*'
    branches:
      - '*'
  pull_request:
    branches: [ main ]

env:
  REPO_FOLDER: ./data_extraction_pipe

jobs:
  linting and sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy
        if [ -f $REPO_FOLDER/requirements.txt ]; then pip install -r $REPO_FOLDER/requirements.txt; fi
  
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 $REPO_FOLDER --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 $REPO_FOLDER --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Mypy check
      run: mypy src

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env: 
           GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_AWS_MLOPS_TOKEN }}
