# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting and sonar

on:
  push:
    tags:
     # add different proper testing for releases
      - '!refs/tags/*'
    branches:
      - '*'
  pull_request:
    branches: [ main ]

env:
  LOCAL_LAMBDA_ARTIFACTS_FOLDER: ./lambda_artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Mypy check
      run: mypy src

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env: 
           GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_AWS_MLOPS_TOKEN }}
    
    - name: Lambda zip and upload to s3
      run: |
        # zip every file in lambda_code directory individually
        mkdir src/lambda_code/lambda_artifacts
        find src/lambda_code -type f -execdir zip '$LOCAL_LAMBDA_ARTIFACTS_FOLDER/{}.zip' '{}' \;

    - name: push zipped code to s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   
          SOURCE_DIR: $LOCAL_LAMBDA_ARTIFACTS_FOLDER
          TARGET_DIR: 'lambda_scripts'
