# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: data extraction pipeline workflow

on:
  push:
    tags:
     # add different proper testing for releases
      - '!refs/tags/*'
    branches:
      - 'main'
    paths:
      - data_extraction_pipe/*.py
      - lambdaDeploy/*.py
      - lambdaGitWatcher/*.py
      - lambdaTraining/*.py
  pull_request:
    branches: [ main ]

env:
  REPO_FOLDER: ./data_extraction_pipe

jobs:
  linting_and_sonar:
    runs-on: ubuntu-latest
    steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env: 
           GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_AWS_MLOPS_TOKEN }}
